### ISSUE TITLE
US9: As an editor, I want to be able to add comments when a post is rejected so the editor knows what changes are needed

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#10]
# TODO

### Backend
- [x]  Update Review Service → add endpoint to comment as review
- [x]  Update Post Service → update endpoint of submitted to reviewable
- [x]  Add tests

### Frontend
- [x]  Update → Add comment input
- [x]  Add tests
