### ISSUE TITLE
US10: As a user I want to be able to comment on a post so I can share my opinion or ask questions

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#11]
# TODO

### Backend
- [x]  Add Comment Service
    - [x]  Add Comment entity
    - [x]  Add Post client
    - [x]  Add endpoint to create comment

### Frontend
- [x]  Update post-list component
    - [x]  Add comments
