### ISSUE TITLE
US11: As a user I want to be able to read comments from other colleagues so that I can get an impression of their opinion or questions about the article

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#12]
# TODO

### Backend
- [x]  Add Comment Service
    - [x]  Add enpoint to get comments by postId

- [x]  Update Post Service
    - [x]  Add Comment entity
    - [x]  Add endpoint to get post with comments by id

### Frontend
- [x]  Update post-list component
    - [x]  View comments
