### ISSUE TITLE
US12: As a user I want to be able to edit or delete my own comments so that I can always correct or delete my own contributions

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#13]
# TODO

### Backend
- [x]  Add Comment Service
    - [x]  Add endpoint to update comment
    - [x]  Add endpoint to delete comment

### Frontend
- [x]  Update post-list component
    - [ ]  Add comment delete function
    - [ ]  Add comment update function
