### ISSUE TITLE
Unit test Frontend US1-5

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#14]
# TODO

### Frontend
- [x]  Add test for `post-list.component.ts`
- [x]  Add test for `post-item.component.ts`
- [x]  Add test for `add-post.component.ts`
- [x]  Add test for `post.service.ts`
- [x]  Add test for `edit-post.component.ts` US3
- [x]  Add test for `post-detail component` US2
- [x]  Add test for `filter.component.ts`
- [x]  Add test for `login component` US1
- [x]  Add test for `home component`
- [x]  Add test for `page-not-found component`
- [x]  Add test for `authentication.service.ts`
- [x]  Add test for routeguards
    - [x]  `confirmLeaveGuard`
    - [x]  `AuthGuard`

![Image](https://github.com/user-attachments/assets/cf074f5a-27de-4aab-8441-2e5f7f007bde)
