### ISSUE TITLE
US1: As an editor, I want to be able to create new posts so I can share news and updates with the organization

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#2]
# TODO

### Backend
- [x]  Set up Post Service
    - [x]  Domain
        - [x]  Post
        - [x]  Category
        - [x]  Status
        - [x]  PostRequest
        - [x]  PostResponse
    - [x]  Repository
    - [x]  Service + interface
    - [x]  Controller
        - [x]  @GetMapping("/") getAllPosts
        - [x]  @GetMapping("/") getPostById
        - [x]  @GetMapping("/enums/categories") getAllPostCategories
        - [x]  @PostMapping("/") addPost
- [x]  Add tests
- [x]  Setup Docker
- [x]  Set up Discovery Service
- [x]  Register Post Service to Discovery
- [x]  Set up Config Service
- [x]  Set up Config for Post Service
- [x]  Set up Gateway
- [x]  Add Gateway route to Post Service
- [x]  Add logback-spring.xml file
- [x]  Add logs

### Frontend
- [x]  Create news-app
- [x]  Set up Tailwind CSS (https://tailwindcss.com/docs/guides/angular)
- [x]  Create Post model
- [x]  Add add-post Component
- [x]  Add navbar component
- [x]  Add post-list component
- [x]  Add post-item component
- [x]  Add Post service 
- [x]  Set up authentication service → login
- [x]  Fix styling
