### ISSUE TITLE
US2: As an editor, I want to be able to save posts as drafts so I can continue working on them later or wait for approval

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#4]
# TODO
### Backend
- [x]  Update Post Service
    - [x]  @GetMapping("/user/{userId}") `getPostsByuserId(@PathVariable Long userId)`
    - [x]  @PostMapping("/submit/{id}") `submitPost(@PathVariable Long id)`
- [x]  Add tests
- [x]  Add logs

### Frontend
- [x]  Add post-detail component + Submit button
- [x]  Update my-post Component
