### ISSUE TITLE
US3: As an editor, I want to be able to edit the content of a post so I can correct errors and update content

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#5]
# TODO
### Backend
- [x]  Update Post Service
    - [x]  @PutMapping("/post/{id}") `editPost(@PathVariable Long id, @RequestBody PostRequest postRequest)`
- [x]  Add tests
- [x]  Add logs

### Frontend
- [x]  Add edit-post component
