### ISSUE TITLE
US4: As a user, I want to be able to see an overview of published posts so that I can stay up to date with the latest news

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#6]
# TODO

### Backend
- [x]  Update Post Service
    - [x]  @GetMapping("/published") `getPublishedPosts()`
- [x]  Add tests
- [x]  Add logs

### Frontend
- [x]  Update post-list component
