### ISSUE TITLE
US7: As editor, I want to be able to review and approve or reject submitted posts so that only approved content is published

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#8]
# TODO

### Backend

- [x]  Update user logic (Reads role or user from header and uses it in logic)
    - [x]  addPost()
    - [x]  submitPost()
    - [x]  editPost()
- [x]  Add tests for user logic updates
- [x]  Update UML
- [x]  Update architecture
- [x]  Set up Review Service
    - [x]  Client
        - [x]  PostClient
    - [x]  Domain
        - [x]  Post
        - [x]  Review
        - [x]  Type
    - [x]  Repository
    - [x]  Service + interface
    - [x]  Controller
        - [x]  @GetMapping("/{id}") `getReviewsByPostId(@PathVariable Long id)`
        - [x]  @PostMapping("/approve") `approve(@RequestBody ReviewRequest reviewRequest)` → `Post Service` [SYNC]
        - [x]  @PostMapping("/reject") `reject(@RequestBody ReviewRequest reviewRequest)` → `Post Service` [SYNC]
- [x]  Add tests for Review Service
- [x]  Setup Docker
- [x]  Register Post Service to Discovery
- [x]  Set up Config for Review Service
- [x]  Add Gateway route to Review Service
- [x]  Add logback-spring.xml file
- [x]  Add logs
- [x]  Update Post Service
    - [x]  Client
        - [x]  Review Client
    - [x]  Domain
        - [x]  Review
        - [x]  ReviewResponse
        - [x]  Post → add reviews
        - [x]  PostResponse → add reviews
    - [x]  Controller
        - [x]  @GetMapping("/submitted") `getSubmittedPosts()`
        - [x]  @GetMapping("/{id}/with-reviews") `getPostByIdWithReviews(@PathVariable Long id)` → `Review Service` [SYNC]
        - [x]  @PostMapping("/publish/{id}") `publishPost(@PathVariable Long id)` → `Review Service` [SYNC]
- [x]  Update endpoints
    - [x]  `/submit/{id}` → `/{id}/submit`
    - [x]  `/publish/{id}` → `/{id}/publish`
- [x]  Update service, when rejecting the post, the post should be a draft again ASYNC
- [x]  Update user info in headers
- [x]  Add tests for Post Service
- [x]  Submitted posts DOES NOT RETURN own posts
- [x]  Add states of “REJECTED” and “APPROVED”
- [x]  Update tests

### Frontend

- [x]  Update navbar component → add route to “reviewPost”
- [x]  Update post-list component
    - [x]  Add list of posts to review
    - [x]  Delete button when on review list
- [x]  Update post-details component
    - [x]  add button to approve and reject
    - [x]  Add list of reviews
- [x]  Create Review model
- [x]  Update Post model
- [x]  Add review-list component
- [x]  Add review-item component
- [x]  Update post-detail component
    - [x]  Add list with review items
    - [x]  Add publish button
- [x]  Add tests
