### ISSUE TITLE
US8: As an editor, I want to be notified when a post is approved or rejected so I know whether it can be published or needs to be revised

### ISSUE THREAD

**Issue by Su-zenGeurtsPXL** [pxlit-projects/project-Su-zenGeurtsPXL-1#9]
# TODO

### Backend
- [x]  Update Post Service
    - [x]  Add notification entity
    - [x]  Add code to create notification after rabbitMQ message
    - [x]  Add endpoint to get notifications by userId
    - [x]  Add endpoint to mark notification as read

### Frontend
- [x]  Update navbar
    - [x]  Add notifications
    - [x]  Add link to correct post
    - [x]  Add code to fetch update for notification to be read
